# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('averageHeight', models.FloatField(null=True)),
                ('surface', models.FloatField(null=True)),
                ('consumption', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetroDepot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('auxConsumption', models.FloatField(null=True)),
                ('ventilationConsumption', models.FloatField(null=True)),
                ('dcConsumption', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usableEnergyContent', models.FloatField(null=True)),
                ('chargingEfficiency', models.FloatField(null=True)),
                ('dischargingEfficiency', models.FloatField(null=True)),
                ('peakPower', models.FloatField(null=True)),
                ('maximumEnergySavingPossiblePerHour', models.FloatField(null=True)),
                ('energySavingMode', models.FloatField(null=True)),
                ('powerLimitToFeed', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetroLineMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('end', models.FloatField(null=True)),
                ('start', models.FloatField(null=True)),
                ('value', models.FloatField(null=True)),
                ('direction', models.CharField(max_length=50)),
                ('metroLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.MetroLine')),
            ],
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField(null=True)),
                ('secondLevelAverageHeight', models.FloatField(null=True)),
                ('secondLevelFloorSurface', models.FloatField(null=True)),
                ('platformSection', models.FloatField(null=True)),
                ('platformAveragePermiter', models.FloatField(null=True)),
                ('minAuxConsumption', models.FloatField(null=True)),
                ('maxAuxConsumption', models.FloatField(null=True)),
                ('minHVACConsumption', models.FloatField(null=True)),
                ('maxHVACConsumption', models.FloatField(null=True)),
                ('tau', models.FloatField(null=True)),
                ('metroLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.MetroLine')),
            ],
        ),
        migrations.CreateModel(
            name='MetroTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crossSection', models.FloatField(null=True)),
                ('averagePerimeter', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('auxiliariesConsumption', models.FloatField(null=True)),
                ('ventilationConsumption', models.FloatField(null=True)),
                ('endStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endstation', to='scene.MetroStation')),
                ('startStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startstation', to='scene.MetroStation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('co2Concentration', models.FloatField()),
                ('solarRadiation', models.FloatField()),
                ('sunElevationAngle', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timeCreation', models.DateTimeField()),
                ('averageMassOfAPassanger', models.FloatField(null=True)),
                ('annualTemperatureAverage', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operationperiod',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Scene'),
        ),
        migrations.AddField(
            model_name='metroline',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Scene'),
        ),
        migrations.AddField(
            model_name='metrodepot',
            name='metroLine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.MetroLine'),
        ),
        migrations.AddField(
            model_name='metroconnection',
            name='firstStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firststation', to='scene.MetroStation'),
        ),
        migrations.AddField(
            model_name='metroconnection',
            name='secondStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondstation', to='scene.MetroStation'),
        ),
    ]
