# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_auto_20170529_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='timeCreation',
            field=models.DateTimeField(verbose_name='Fecha de creaci\xf3n'),
        ),
    ]
