# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import scene.models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_scene_step2template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='step2Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage, upload_to='step2Template/'),
        ),
    ]
