# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_auto_20170529_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('In', 'Incompleto'), ('OK', 'Completo')], default='In', max_length=2, verbose_name='Estado'),
        ),
    ]
