# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import scene.models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_auto_20170615_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='step2File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step2File/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='step2Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step2Template/'),
        ),
    ]
