# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0004_scene_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='lastSuccessfullStep',
            field=models.IntegerField(default=1),
        ),
    ]
