# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import scene.models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0004_auto_20170618_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='step4File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step4File/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step4Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step4Template/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step6File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step6File/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step6Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step6Template/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step7File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step7File/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step7Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step7Template/'),
        ),
    ]
