# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0005_auto_20170618_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='lastSuccessfullStep',
        ),
        migrations.AddField(
            model_name='scene',
            name='currentStep',
            field=models.IntegerField(default=0, verbose_name='Paso actual'),
        ),
    ]
