# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0005_scene_lastsuccessfullstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='lastSuccessfullStep',
            field=models.IntegerField(default=0),
        ),
    ]
