# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0007_auto_20170612_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='lastSuccessfullStep',
            field=models.IntegerField(default=1, verbose_name='Paso pendiente'),
        ),
    ]
