# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0008_auto_20170705_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationperiod',
            name='externalId',
            field=models.UUIDField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationperiod',
            name='isOld',
            field=models.BooleanField(default=False),
        ),
    ]
