# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0008_auto_20170613_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='lastSuccessfullStep',
            field=models.IntegerField(default=0, verbose_name='Paso pendiente'),
        ),
    ]
