# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0009_auto_20170613_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metroconnection',
            old_name='averageHeight',
            new_name='avgHeight',
        ),
        migrations.RenameField(
            model_name='metroconnection',
            old_name='surface',
            new_name='avgSurface',
        ),
        migrations.RemoveField(
            model_name='metroconnection',
            name='firstStation',
        ),
        migrations.RemoveField(
            model_name='metroconnection',
            name='secondStation',
        ),
        migrations.AddField(
            model_name='metroconnection',
            name='externalId',
            field=models.UUIDField(default=uuid.UUID('c017c392-005d-4024-8cc0-70d04fdd70b1')),
        ),
        migrations.AddField(
            model_name='metroconnection',
            name='scene',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='scene.Scene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metroconnection',
            name='stations',
            field=models.ManyToManyField(to='scene.MetroStation'),
        ),
        migrations.AddField(
            model_name='metroline',
            name='externalId',
            field=models.UUIDField(default=uuid.UUID('9b087e2b-42da-4c45-8a85-051733a408b7')),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='externalId',
            field=models.UUIDField(default=uuid.UUID('1c0592c8-933c-4c1a-8fef-7c9245808496')),
        ),
    ]
