# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import scene.models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0009_auto_20170707_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='step2File',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='step2Template',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='step4File',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='step4Template',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='step7File',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='step7Template',
        ),
        migrations.AddField(
            model_name='scene',
            name='step1File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step1File/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step1Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step1Template/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step3File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step3File/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step3Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step3Template/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step5File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step5File/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='step5Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step5Template/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='step6File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step5File/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='step6Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step5Template/'),
        ),
    ]
