# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0013_auto_20170713_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrolinemetric',
            name='metric',
            field=models.CharField(choices=[('S', ''), ('CR', ''), ('SL', ''), ('G', '')], max_length=50),
        ),
    ]
