# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0014_auto_20170713_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrolinemetric',
            name='direction',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
