# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0015_auto_20170713_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationPeriodForMetroLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('frequency', 'trains/hour'), ('receptivity', '%'), ('percentageDCDistributionLosses', '%'), ('PercentageACSubstationLossesFeedEntireSystem', ''), ('PercentageACSubstationLossesFeedEntireSystem', ''), ('PercentageDCSubstationLosses', '')], max_length=50, null=True)),
                ('value', models.FloatField(null=True)),
                ('direction', models.CharField(choices=[('g', ''), ('r', '')], max_length=50, null=True)),
                ('metroLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.MetroLine')),
                ('operationPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.OperationPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='OperationPeriodForMetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('ventilationFlow', 'm^3/s'), ('dwellTime', 'seg'), ('PassengersInStations', '')], max_length=50, null=True)),
                ('value', models.FloatField(null=True)),
                ('direction', models.CharField(choices=[('g', ''), ('r', '')], max_length=50, null=True)),
                ('metroStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.MetroStation')),
                ('operationPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.OperationPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='OperationPeriodForMetroTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('PassengersTravelingBetweenStations', ''), ('MaxTravelTimeBetweenStations', 'seg')], max_length=50, null=True)),
                ('value', models.FloatField(null=True)),
                ('direction', models.CharField(choices=[('g', ''), ('r', '')], max_length=50, null=True)),
                ('metroTrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.MetroTrack')),
                ('operationPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.OperationPeriod')),
            ],
        ),
        migrations.AlterField(
            model_name='metrolinemetric',
            name='direction',
            field=models.CharField(choices=[('g', ''), ('r', '')], max_length=50, null=True),
        ),
    ]
