# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0016_auto_20170714_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='timeStampStep1File',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='timeStampStep3File',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='timeStampStep5File',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='timeStampStep6File',
            field=models.DateTimeField(null=True),
        ),
    ]
