# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    MetroTrack = apps.get_model('scene', 'MetroTrack')
    for track in MetroTrack.objects.all():
        track.externalId = uuid.uuid4()
        track.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0017_auto_20170806_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrotrack',
            name='externalId',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(create_uuid)
    ]
