# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0018_metrotrack_externalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrotrack',
            name='externalId',
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False)
        )
    ]
