# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import scene.models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0019_auto_20171002_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='step6File',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step6File/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='step6Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='ste6Template/'),
        ),
        migrations.AlterUniqueTogether(
            name='metroconnection',
            unique_together=set([('scene', 'name')]),
        ),
    ]
