# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import scene.models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0020_auto_20171114_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='step6Template',
            field=models.FileField(null=True, storage=scene.models.OverwriteStorage(), upload_to='step6Template/'),
        ),
    ]
