# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos_Cables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cable_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('En_operacion', models.FloatField()),
                ('Term_ID1', models.CharField(max_length=100)),
                ('Term_ID2', models.CharField(max_length=100)),
                ('Largo', models.FloatField()),
                ('Snom', models.FloatField()),
                ('Resistencia', models.FloatField()),
                ('Reactancia', models.FloatField()),
                ('Capacitancia', models.FloatField()),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_CDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDC_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('Term_ID', models.CharField(max_length=100)),
                ('Vnom', models.FloatField()),
                ('Snom', models.FloatField()),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_Lineas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linea_ID', models.CharField(max_length=100)),
                ('Vnom', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_PVAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PVac_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('Term_ID', models.CharField(max_length=100)),
                ('En_operacion', models.BooleanField()),
                ('Vnom', models.FloatField()),
                ('Snom', models.FloatField()),
                ('PerfilPV', models.CharField(max_length=100)),
                ('cosphi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_PVdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PVdc_ID', models.CharField(max_length=100)),
                ('Linea_ID', models.CharField(max_length=100)),
                ('Via', models.CharField(max_length=100)),
                ('PosVia', models.CharField(max_length=100)),
                ('En_operacion', models.BooleanField()),
                ('PerfilPV', models.CharField(max_length=100)),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_SAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAF_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('Term_ID', models.CharField(max_length=100)),
                ('En_operacion', models.BooleanField()),
                ('Vac', models.FloatField()),
                ('Snom', models.FloatField()),
                ('Consumo_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_SER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SER_ID', models.CharField(max_length=100)),
                ('Linea_ID', models.CharField(max_length=100)),
                ('Via_ID', models.CharField(max_length=100)),
                ('Term_ID', models.CharField(max_length=100)),
                ('En_operacion', models.BooleanField()),
                ('PosVia', models.FloatField()),
                ('Resistencia', models.FloatField()),
                ('Vdc', models.FloatField()),
                ('Vac', models.FloatField()),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_Terminales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('Vnom', models.FloatField()),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_Trafos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trafo_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('En_operacion', models.BooleanField()),
                ('Snom', models.FloatField()),
                ('HVTerm_ID', models.CharField(max_length=100)),
                ('LVTerm_ID', models.CharField(max_length=100)),
                ('Resistencia', models.FloatField()),
                ('Reactancia', models.FloatField()),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_Trenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tren_ID', models.CharField(max_length=100)),
                ('Linea_ID', models.CharField(max_length=100)),
                ('Via_ID', models.CharField(max_length=100)),
                ('En_operacion', models.BooleanField()),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributos_Vias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Via_ID', models.CharField(max_length=100)),
                ('Linea_ID', models.CharField(max_length=100)),
                ('Largo', models.FloatField()),
                ('Resistividad', models.FloatField()),
                ('Nrieles', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_trenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tren_ID', models.CharField(max_length=100)),
                ('Linea_ID', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Via', models.CharField(max_length=100)),
                ('Posicion', models.FloatField()),
                ('Velocidad', models.FloatField()),
                ('Aceleracion', models.FloatField()),
                ('Potencia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Elementos_DC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elemento_ID', models.CharField(max_length=100)),
                ('Linea_ID', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('En_operacion', models.BooleanField()),
                ('Save', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles_PV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Perfil_ID', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('P', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles_SAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumo_ID', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('P', models.FloatField()),
                ('Q', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sim_ID', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Branch_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('Pf', models.FloatField()),
                ('Qf', models.FloatField()),
                ('Ploss', models.FloatField()),
                ('Qloss', models.FloatField()),
                ('Loading', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_Elementos_DC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sim_ID', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Elemento_ID', models.CharField(max_length=100)),
                ('Linea_ID', models.CharField(max_length=100)),
                ('V', models.FloatField()),
                ('P', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_Terminales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sim_ID', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Term_ID', models.CharField(max_length=100)),
                ('Red_ID', models.CharField(max_length=100)),
                ('V', models.FloatField()),
                ('delta', models.FloatField()),
                ('P', models.FloatField()),
                ('Q', models.FloatField()),
            ],
        ),
    ]
