# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos_vias',
            name='Nrieles',
            field=models.IntegerField(),
        ),
    ]
