# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0002_auto_20180428_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos_cables',
            name='En_operacion',
            field=models.BooleanField(),
        ),
    ]
