# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0003_auto_20180428_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributos_trenes',
            name='p0',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atributos_trenes',
            name='x0',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
