# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0005_auto_20180429_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos_pvdc',
            name='PosVia',
            field=models.FloatField(),
        ),
    ]
