# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0006_auto_20180429_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen_Simulaciones_DC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_ser', models.FloatField()),
                ('e_trenes', models.FloatField()),
                ('e_perdidas', models.FloatField()),
                ('e_almacenable', models.FloatField()),
            ],
        ),
    ]
