# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0007_resumen_simulaciones_dc'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen_simulaciones_dc',
            name='sim_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
