# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0008_resumen_simulaciones_dc_sim_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Branch_ID',
            new_name='branch_id',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Loading',
            new_name='loading',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Pf',
            new_name='pf',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Ploss',
            new_name='ploss',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Qf',
            new_name='qf',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Qloss',
            new_name='qloss',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Red_ID',
            new_name='red_id',
        ),
        migrations.RenameField(
            model_name='resultados_branch',
            old_name='Sim_ID',
            new_name='sim_id',
        ),
        migrations.RenameField(
            model_name='resultados_elementos_dc',
            old_name='Elemento_ID',
            new_name='elemento_id',
        ),
        migrations.RenameField(
            model_name='resultados_elementos_dc',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='resultados_elementos_dc',
            old_name='Linea_ID',
            new_name='linea_id',
        ),
        migrations.RenameField(
            model_name='resultados_elementos_dc',
            old_name='P',
            new_name='p',
        ),
        migrations.RenameField(
            model_name='resultados_elementos_dc',
            old_name='Sim_ID',
            new_name='sim_id',
        ),
        migrations.RenameField(
            model_name='resultados_elementos_dc',
            old_name='V',
            new_name='v',
        ),
        migrations.RenameField(
            model_name='resultados_terminales',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='resultados_terminales',
            old_name='P',
            new_name='p',
        ),
        migrations.RenameField(
            model_name='resultados_terminales',
            old_name='Q',
            new_name='q',
        ),
        migrations.RenameField(
            model_name='resultados_terminales',
            old_name='Red_ID',
            new_name='red_id',
        ),
        migrations.RenameField(
            model_name='resultados_terminales',
            old_name='Sim_ID',
            new_name='sim_id',
        ),
        migrations.RenameField(
            model_name='resultados_terminales',
            old_name='Term_ID',
            new_name='term_id',
        ),
        migrations.RenameField(
            model_name='resultados_terminales',
            old_name='V',
            new_name='v',
        ),
    ]
