# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energycentermodel', '0009_auto_20180430_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos_ser',
            name='PosVia',
            field=models.IntegerField(),
        ),
    ]
