# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scene', '0017_auto_20170806_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('clusterFile', models.CharField(max_length=100, verbose_name='archivo bash')),
            ],
        ),
        migrations.CreateModel(
            name='ModelExecutionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Tiempo de inicio')),
                ('end', models.DateTimeField(null=True, verbose_name='Tiempo de fin')),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('ok', 'Terminado exitosamente'), ('error', 'Terminado con error'), ('cancel', 'Cancelado por el usuario')], default='running', max_length=40, verbose_name='Estado')),
                ('jobNumber', models.BigIntegerField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmmodel.Model')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='ModelExecutionQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmmodel.Model')),
                ('modelExecutionHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmmodel.ModelExecutionHistory')),
            ],
        ),
    ]
