# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0006_auto_20170903_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelexecutionhistory',
            name='externalId',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
