# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0007_modelexecutionhistory_externalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='clusterFile',
            new_name='clusterExecutionId',
        ),
    ]
