# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0008_auto_20170910_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelexecutionhistory',
            old_name='error',
            new_name='std_err',
        ),
        migrations.AddField(
            model_name='modelexecutionhistory',
            name='std_out',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
