# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0010_auto_20170913_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelexecutionhistory',
            name='answer',
            field=models.FileField(null=True, upload_to='modelOutput/'),
        ),
        migrations.AlterField(
            model_name='modelexecutionhistory',
            name='status',
            field=models.CharField(choices=[('running', 'En ejecución'), ('ok', 'Terminado exitosamente'), ('error', 'Terminado con error'), ('error to start', 'Error al iniciar'), ('cancel', 'Cancelado por el usuario')], default='running', max_length=40, verbose_name='Estado'),
        ),
    ]
