# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0011_auto_20170919_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='visible',
        ),
    ]
