# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0012_remove_model_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='vizURL',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
