# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0013_model_vizurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelexecutionhistory',
            name='status',
            field=models.CharField(choices=[('running', 'En ejecución'), ('ok', 'Terminado exitosamente'), ('error', 'Terminado con error'), ('error to start', 'Error al iniciar'), ('cancel', 'Cancelado por el usuario'), ("cluster didn't send answer", 'Clúster no informó respuesta')], default='running', max_length=40, verbose_name='Estado'),
        ),
    ]
