# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0015_modelexecutionhistory_check_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelexecutionhistory',
            name='downloadFile',
            field=models.FileField(null=True, upload_to='modelOuputFile/'),
        ),
        migrations.AddField(
            model_name='modelexecutionhistory',
            name='timestampFile',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
