# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0017_auto_20171013_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='CMMModel',
        ),
    ]
