# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmmodel', '0018_auto_20180405_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmmmodel',
            name='modelRequired',
            field=models.IntegerField(null=True),
        ),
    ]
