# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osirisuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='OsirisUser',
        ),
    ]
