# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmmmodel', '0012_remove_model_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('section', models.IntegerField(null=True)),
                ('attributeName', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('value', models.FloatField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmmodel.ModelExecutionHistory')),
            ],
        ),
    ]
