# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0002_auto_20170924_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanswer',
            name='direction',
            field=models.CharField(max_length=1),
        ),
    ]
