# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0003_auto_20170924_0138'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='modelanswer',
            index=models.Index(fields=['execution', 'line', 'direction', 'operation', 'track'], name='viz_modelan_executi_4848c9_idx'),
        ),
    ]
