# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0017_auto_20170806_1736'),
        ('viz', '0004_auto_20170924_0806'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='modelanswer',
            name='viz_modelan_executi_4848c9_idx',
        ),
        migrations.RemoveField(
            model_name='modelanswer',
            name='line',
        ),
        migrations.RemoveField(
            model_name='modelanswer',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='modelanswer',
            name='track',
        ),
        migrations.AddField(
            model_name='modelanswer',
            name='metroLine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scene.MetroLine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelanswer',
            name='metroTrack',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scene.MetroTrack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelanswer',
            name='operationPeriod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scene.OperationPeriod'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='modelanswer',
            index=models.Index(fields=['execution', 'metroLine', 'direction', 'operationPeriod', 'metroTrack'], name='viz_modelan_executi_73da4b_idx'),
        ),
    ]
