# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0007_auto_20171120_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanswer',
            name='metroLine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.MetroLine'),
        ),
        migrations.AlterField(
            model_name='modelanswer',
            name='operationPeriod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.OperationPeriod'),
        ),
    ]
