# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0009_heatmodeltableanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatmodeltableanswer',
            name='group',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
