# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-04 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0021_auto_20171129_0451'),
        ('viz', '0010_heatmodeltableanswer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatmodeltableanswer',
            name='direction',
        ),
        migrations.AddField(
            model_name='heatmodeltableanswer',
            name='operationPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scene.OperationPeriod'),
            preserve_default=False,
        ),
    ]
