# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0012_energycentermodelanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycentermodelanswer',
            name='metroLine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='energycentermodelanswer',
            name='via',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
