# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0013_auto_20180509_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energycentermodelanswer',
            old_name='attributeName',
            new_name='chartName',
        ),
        migrations.AddField(
            model_name='energycentermodelanswer',
            name='groupName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
